theme: jekyll-theme-minimal

title： 博客的名字
author： 博主的名字
baseurl： 博客的根地址==你的文件夹名称（默认为bohu-jekyll-theme），如果你更改了文件夹名称，请把此处也修改掉。
description： head中的网页描述信息。简要描述你的网站，让搜索引擎能更好的收录你的网站。

选填信息：
email： 你的邮箱地址
twitter_username: 你的推特用户名
weibo_username: 你的微博用户名
github_username: 你的github用户名
以上四项信息你填写了之后博主信息栏里会自动出现相应的链接图标，不填就不会出现。

disqus_shortname: 你的disqus帐号
duoshuo——shortname： 你的多说帐号
